### ISSUE TITLE
Request for x86 adb & fastboot binaries

### ISSUE THREAD

**Issue by Alastor27** [Magisk-Modules-Repo/adb-Installer#4]
Greatings!
I would like to make a request for x86 adb & fastboot binaries, if possible.
Thank you for your attention. I’m looking forward to your reply.

**Comment by osm0sis** [comment]
I don't compile these, of course, as you can read in my README.md, I merely curate the builds into a package and wrote the necessary wrapper for them to function with no further setup. The arm builds should work on most (if not all) x86 Android devices due to the libhoudini layer they include. arm also works on arm64, so arm builds provide the highest compatibility in a single binary, which is why I use them.

If you really need x86 binaries, you should be able to grab them from platform-tools in the Android SDK for Linux x86, as Linux x86 = Android x86 for most scenarios.

**Comment by Alastor27** [comment]
@osm0sis
Thank you very much for the information.
I will try and get the binaries from the platform-tools then.
Best regards!

**Comment by osm0sis** [comment]
r23 might be the last for Linux 32-bit: https://androidsdkoffline.blogspot.ca/p/android-sdk-platform-tools.html
